### PR TITLE
Create Component + Redux Structures

### PR DESCRIPTION
**Pull request by RosaTheDev**
____ Wrote Tests/ __x__ Implemented /____ Reviewed

## Necessary checkmarks:

    [ ] All Tests are Passing in all environments

    [x] The code will run locally

## Type of change

    [x] New feature
    [] Bug Fix
    [] Refactor

## Description of Change:
Description: 
Created Files for each component and created component structure 
    
## Requested feedback: 
    
I'd like feedback on... How does everything look so far? are we forgetting any files? 

## Check the correct boxes

    [x] This broke nothing
    [] This broke some stuff
    [] This broke everything

## Testing Changes

    [] No Tests have been changed
    [] Some Tests have been changed
    [] All of the Tests have been changed(Please describe what in the world happened)

## Checklist:

    [x] My code has no unused/commented out code
    [x] My code has no console.logs
    [x] I have reviewed my code
    [] I have commented my code, particularly in hard-to-understand areas
    [] I have fully tested my code

(For Fun!)Please Include a link to a gif of your feelings about this branch

Link: 
happy

### CODE REVIEW

**Review by oswhytecodes — COMMENTED** [review]
The file components are looking good, just one more thing.
Add a pull request template and we are good to go.

**Comment by RosaTheDev** [comment]
My bad, let me add the PR template real quick and I'll get right back at you

**Comment by RosaTheDev** [comment]
Just added the PR Template file, ready for final review

**Review by oswhytecodes — APPROVED** [review]
perfect, we are good to go

**Pull request merged**
